name: intelligent_ordering_system
description: Mobile app for suggestions of items according to emotions

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  firebase_ml_vision: ^0.9.3
  image_picker: ^0.6.1+10
  share:
  package_info:
  url_launcher: ^5.0.3
  google_maps_flutter: any
  provider: any
  location: any
  avatar_glow:
  clippy_flutter: ^1.1.0
  navigate: ^1.0.1
  transparent_image: ^1.0.0
  toast: ^0.1.3
  flare_splash_screen: any
  charts_flutter: ^0.6.0
  intl:
  shared_preferences: ^0.5.3+4
  dio:
  flushbar: ^1.8.2
  progress_dialog: ^1.1.0+1
  flutter_svg: ^0.14.0
  basic_utils: ^1.8.2
  modal_progress_hud: ^0.1.3
  connectivity:
  pull_to_refresh: ^1.5.6
  get_it: ^1.0.3
  cached_network_image: ^1.1.1
  carousel_slider: ^1.3.1
  loading: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/launcher/
    - assets/flare/
    - assets/images/
    - assets/images/banner/
    - assets/images/items/beef/
    - assets/images/items/chicken/
    - assets/images/items/pork/
    - assets/images/items/seafood/
    - assets/images/items/vegetables/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

    - family: boxicons
      fonts:
        - asset: assets/fonts/boxicons.ttf

    - family: fontello
      fonts:
        - asset: assets/fonts/fontello.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
